POST  http://localhost:3333/employees
Content-Type: application/json

{
    "email": "teste@gmail.com",
    "name": "Joao Pedro",
    "salary": 3000
}

###

GET http://localhost:3333/employees

###
PUT http://localhost:3333/employees/1
Content-Type: application/json

{
    "email": "teste2@gmail.com",
    "name": "Joao Pedro Novo",
    "salary": 2500
}

###

DELETE http://localhost:3333/treinos/03ce1c15-28ef-45b4-89fb-c2d527a7bc1a